export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type TaskProgressMode = "manual" | "quantity";
export type KpiDirection = "higher_is_better" | "lower_is_better";
export type KpiCalculationMethod = "auto" | "manual" | "semi_auto";
export type KpiFrequency = "daily" | "weekly" | "monthly" | "quarterly" | "yearly";
export type KpiVisibility = "management" | "project_managers" | "team";
export type KpiPeriodType = "monthly" | "quarterly";
export type KpiStatus = "green" | "yellow" | "red" | "neutral";
export type KpiTrend = "up" | "down" | "flat" | "unknown";
export type KpiValueSource = "auto" | "manual" | "semi_auto";

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          email: string | null;
          avatar_url: string | null;
          role: "admin" | "project_manager" | "member";
          active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          full_name?: string | null;
          email?: string | null;
          avatar_url?: string | null;
          role?: "admin" | "project_manager" | "member";
          active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          email?: string | null;
          avatar_url?: string | null;
          role?: "admin" | "project_manager" | "member";
          active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      projects: {
        Row: {
          id: string;
          legacy_project_id: string | null;
          name: string;
          manager_id: string | null;
          manager_name: string | null;
          path: string | null;
          current_stage: string | null;
          status: "active" | "paused" | "completed" | "cancelled";
          start_date: string | null;
          end_date: string | null;
          total_budget: number | null;
          description: string | null;
          logo_url: string | null;
          forms_owner_id: string | null;
          progress: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_project_id?: string | null;
          name?: string;
          manager_id?: string | null;
          manager_name?: string | null;
          path?: string | null;
          current_stage?: string | null;
          status?: "active" | "paused" | "completed" | "cancelled";
          start_date?: string | null;
          end_date?: string | null;
          total_budget?: number | null;
          description?: string | null;
          logo_url?: string | null;
          forms_owner_id?: string | null;
          progress?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_project_id?: string | null;
          name?: string;
          manager_id?: string | null;
          manager_name?: string | null;
          path?: string | null;
          current_stage?: string | null;
          status?: "active" | "paused" | "completed" | "cancelled";
          start_date?: string | null;
          end_date?: string | null;
          total_budget?: number | null;
          description?: string | null;
          logo_url?: string | null;
          forms_owner_id?: string | null;
          progress?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      project_members: {
        Row: {
          id: string;
          project_id: string;
          user_id: string;
          role_in_project: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id?: string;
          user_id?: string;
          role_in_project?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          user_id?: string;
          role_in_project?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      tasks: {
        Row: {
          id: string;
          legacy_task_id: string | null;
          project_id: string;
          title: string;
          sub_task: string | null;
          category: string | null;
          owner_id: string | null;
          owner_name: string | null;
          status: "Backlog" | "To Do" | "In Progress" | "Review" | "Done" | "Cancelled";
          board_column: string;
          priority: "low" | "medium" | "high" | "critical";
          start_date: string | null;
          due_date: string | null;
          cost: number | null;
          quantity_total: number | null;
          quantity_done: number | null;
          progress_mode: TaskProgressMode;
          progress: number | null;
          schedule_status: string | null;
          alert_level: "Low" | "Medium" | "High" | "Critical" | null;
          alert_message: string | null;
          alert_action: string | null;
          days_to_due: number | null;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          legacy_task_id?: string | null;
          project_id?: string;
          title?: string;
          sub_task?: string | null;
          category?: string | null;
          owner_id?: string | null;
          owner_name?: string | null;
          status?: "Backlog" | "To Do" | "In Progress" | "Review" | "Done" | "Cancelled";
          board_column?: string;
          priority?: "low" | "medium" | "high" | "critical";
          start_date?: string | null;
          due_date?: string | null;
          cost?: number | null;
          quantity_total?: number | null;
          quantity_done?: number | null;
          progress_mode?: TaskProgressMode;
          progress?: number | null;
          schedule_status?: string | null;
          alert_level?: "Low" | "Medium" | "High" | "Critical" | null;
          alert_message?: string | null;
          alert_action?: string | null;
          days_to_due?: number | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          legacy_task_id?: string | null;
          project_id?: string;
          title?: string;
          sub_task?: string | null;
          category?: string | null;
          owner_id?: string | null;
          owner_name?: string | null;
          status?: "Backlog" | "To Do" | "In Progress" | "Review" | "Done" | "Cancelled";
          board_column?: string;
          priority?: "low" | "medium" | "high" | "critical";
          start_date?: string | null;
          due_date?: string | null;
          cost?: number | null;
          quantity_total?: number | null;
          quantity_done?: number | null;
          progress_mode?: TaskProgressMode;
          progress?: number | null;
          schedule_status?: string | null;
          alert_level?: "Low" | "Medium" | "High" | "Critical" | null;
          alert_message?: string | null;
          alert_action?: string | null;
          days_to_due?: number | null;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      challenges: {
        Row: {
          id: string;
          project_id: string;
          task_id: string | null;
          form_instance_id: string | null;
          title: string;
          description: string | null;
          status: "open" | "in_progress" | "resolved" | "closed";
          owner_id: string | null;
          risk_impact: string | null;
          risk_type: string | null;
          resolution: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id?: string;
          task_id?: string | null;
          form_instance_id?: string | null;
          title?: string;
          description?: string | null;
          status?: "open" | "in_progress" | "resolved" | "closed";
          owner_id?: string | null;
          risk_impact?: string | null;
          risk_type?: string | null;
          resolution?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          task_id?: string | null;
          form_instance_id?: string | null;
          title?: string;
          description?: string | null;
          status?: "open" | "in_progress" | "resolved" | "closed";
          owner_id?: string | null;
          risk_impact?: string | null;
          risk_type?: string | null;
          resolution?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      documents: {
        Row: {
          id: string;
          project_id: string;
          task_id: string | null;
          title: string;
          url: string | null;
          file_path: string | null;
          type: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          project_id?: string;
          task_id?: string | null;
          title?: string;
          url?: string | null;
          file_path?: string | null;
          type?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          task_id?: string | null;
          title?: string;
          url?: string | null;
          file_path?: string | null;
          type?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      project_form_templates: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          category: string | null;
          stage: string | null;
          applies_to_path: string | null;
          template_kind: "form" | "docx" | "xlsx" | "hybrid";
          schema_json: Json;
          source_file_path: string | null;
          active: boolean;
          sort_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          category?: string | null;
          stage?: string | null;
          applies_to_path?: string | null;
          template_kind?: "form" | "docx" | "xlsx" | "hybrid";
          schema_json?: Json;
          source_file_path?: string | null;
          active?: boolean;
          sort_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          category?: string | null;
          stage?: string | null;
          applies_to_path?: string | null;
          template_kind?: "form" | "docx" | "xlsx" | "hybrid";
          schema_json?: Json;
          source_file_path?: string | null;
          active?: boolean;
          sort_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      project_form_instances: {
        Row: {
          id: string;
          project_id: string;
          template_id: string;
          assigned_owner_id: string | null;
          status: "not_started" | "draft" | "completed";
          data_json: Json;
          completion_percentage: number | null;
          created_by: string | null;
          updated_by: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          template_id: string;
          assigned_owner_id?: string | null;
          status?: "not_started" | "draft" | "completed";
          data_json?: Json;
          completion_percentage?: number | null;
          created_by?: string | null;
          updated_by?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          template_id?: string;
          assigned_owner_id?: string | null;
          status?: "not_started" | "draft" | "completed";
          data_json?: Json;
          completion_percentage?: number | null;
          created_by?: string | null;
          updated_by?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      project_form_shares: {
        Row: {
          id: string;
          form_instance_id: string;
          shared_with_user_id: string | null;
          permission: "view" | "edit";
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          form_instance_id: string;
          shared_with_user_id?: string | null;
          permission?: "view" | "edit";
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          form_instance_id?: string;
          shared_with_user_id?: string | null;
          permission?: "view" | "edit";
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      kpi_definitions: {
        Row: {
          id: string;
          code: string;
          name: string;
          description: string | null;
          perspective: string;
          strategic_goal: string | null;
          measurement_label: string | null;
          target_value: number | null;
          target_text: string | null;
          target_unit: string | null;
          direction: KpiDirection;
          calculation_method: KpiCalculationMethod;
          auto_source: string | null;
          frequency: KpiFrequency;
          visibility: KpiVisibility;
          owner_id: string | null;
          active: boolean;
          sort_order: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          code: string;
          name: string;
          description?: string | null;
          perspective: string;
          strategic_goal?: string | null;
          measurement_label?: string | null;
          target_value?: number | null;
          target_text?: string | null;
          target_unit?: string | null;
          direction?: KpiDirection;
          calculation_method?: KpiCalculationMethod;
          auto_source?: string | null;
          frequency?: KpiFrequency;
          visibility?: KpiVisibility;
          owner_id?: string | null;
          active?: boolean;
          sort_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          code?: string;
          name?: string;
          description?: string | null;
          perspective?: string;
          strategic_goal?: string | null;
          measurement_label?: string | null;
          target_value?: number | null;
          target_text?: string | null;
          target_unit?: string | null;
          direction?: KpiDirection;
          calculation_method?: KpiCalculationMethod;
          auto_source?: string | null;
          frequency?: KpiFrequency;
          visibility?: KpiVisibility;
          owner_id?: string | null;
          active?: boolean;
          sort_order?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      kpi_values: {
        Row: {
          id: string;
          kpi_id: string;
          period_type: KpiPeriodType;
          period_start: string;
          period_end: string;
          actual_value: number | null;
          actual_text: string | null;
          target_value: number | null;
          status: KpiStatus | null;
          trend: KpiTrend | null;
          source: KpiValueSource;
          notes: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          kpi_id: string;
          period_type?: KpiPeriodType;
          period_start: string;
          period_end: string;
          actual_value?: number | null;
          actual_text?: string | null;
          target_value?: number | null;
          status?: KpiStatus | null;
          trend?: KpiTrend | null;
          source?: KpiValueSource;
          notes?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          kpi_id?: string;
          period_type?: KpiPeriodType;
          period_start?: string;
          period_end?: string;
          actual_value?: number | null;
          actual_text?: string | null;
          target_value?: number | null;
          status?: KpiStatus | null;
          trend?: KpiTrend | null;
          source?: KpiValueSource;
          notes?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      kpi_share_links: {
        Row: {
          id: string;
          name: string;
          token_hash: string;
          active: boolean;
          expires_at: string | null;
          created_by: string | null;
          last_viewed_at: string | null;
          views_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name?: string;
          token_hash: string;
          active?: boolean;
          expires_at?: string | null;
          created_by?: string | null;
          last_viewed_at?: string | null;
          views_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          token_hash?: string;
          active?: boolean;
          expires_at?: string | null;
          created_by?: string | null;
          last_viewed_at?: string | null;
          views_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      indicator_products: {
        Row: {
          id: string;
          kpi_id: string | null;
          name: string;
          category: string | null;
          description: string | null;
          current_value: number;
          target_value: number | null;
          unit: string | null;
          status: "active" | "paused" | "archived";
          owner_id: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          kpi_id?: string | null;
          name: string;
          category?: string | null;
          description?: string | null;
          current_value?: number;
          target_value?: number | null;
          unit?: string | null;
          status?: "active" | "paused" | "archived";
          owner_id?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          kpi_id?: string | null;
          name?: string;
          category?: string | null;
          description?: string | null;
          current_value?: number;
          target_value?: number | null;
          unit?: string | null;
          status?: "active" | "paused" | "archived";
          owner_id?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      project_performance_updates: {
        Row: {
          id: string;
          project_id: string;
          period_type: KpiPeriodType;
          period_start: string;
          period_end: string;
          planned_progress: number;
          actual_progress: number;
          actual_cost: number;
          notes: string | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          project_id: string;
          period_type?: KpiPeriodType;
          period_start: string;
          period_end: string;
          planned_progress?: number;
          actual_progress?: number;
          actual_cost?: number;
          notes?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          project_id?: string;
          period_type?: KpiPeriodType;
          period_start?: string;
          period_end?: string;
          planned_progress?: number;
          actual_progress?: number;
          actual_cost?: number;
          notes?: string | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      comments: {
        Row: {
          id: string;
          task_id: string;
          user_id: string | null;
          body: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          task_id?: string;
          user_id?: string | null;
          body?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          task_id?: string;
          user_id?: string | null;
          body?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          project_id: string | null;
          task_id: string | null;
          type: string | null;
          title: string | null;
          body: string | null;
          sent_via: string | null;
          sent_at: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          project_id?: string | null;
          task_id?: string | null;
          type?: string | null;
          title?: string | null;
          body?: string | null;
          sent_via?: string | null;
          sent_at?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          project_id?: string | null;
          task_id?: string | null;
          type?: string | null;
          title?: string | null;
          body?: string | null;
          sent_via?: string | null;
          sent_at?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      automation_logs: {
        Row: {
          id: string;
          type: string | null;
          status: string | null;
          payload: Json | null;
          error: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          type?: string | null;
          status?: string | null;
          payload?: Json | null;
          error?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          type?: string | null;
          status?: string | null;
          payload?: Json | null;
          error?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      project_templates: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          category: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name?: string;
          description?: string | null;
          category?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          category?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      task_templates: {
        Row: {
          id: string;
          template_id: string;
          title: string;
          sub_task: string | null;
          category: string | null;
          default_duration_days: number | null;
          default_priority: string;
          sort_order: number;
        };
        Insert: {
          id?: string;
          template_id?: string;
          title?: string;
          sub_task?: string | null;
          category?: string | null;
          default_duration_days?: number | null;
          default_priority?: string;
          sort_order?: number;
        };
        Update: {
          id?: string;
          template_id?: string;
          title?: string;
          sub_task?: string | null;
          category?: string | null;
          default_duration_days?: number | null;
          default_priority?: string;
          sort_order?: number;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};

export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Project = Database["public"]["Tables"]["projects"]["Row"];
export type ProjectMember = Database["public"]["Tables"]["project_members"]["Row"];
export type Task = Database["public"]["Tables"]["tasks"]["Row"];
export type Challenge = Database["public"]["Tables"]["challenges"]["Row"];
export type Document = Database["public"]["Tables"]["documents"]["Row"];
export type ProjectFormTemplate = Database["public"]["Tables"]["project_form_templates"]["Row"];
export type ProjectFormInstance = Database["public"]["Tables"]["project_form_instances"]["Row"];
export type ProjectFormShare = Database["public"]["Tables"]["project_form_shares"]["Row"];
export type KpiDefinition = Database["public"]["Tables"]["kpi_definitions"]["Row"];
export type KpiValue = Database["public"]["Tables"]["kpi_values"]["Row"];
export type KpiShareLink = Database["public"]["Tables"]["kpi_share_links"]["Row"];
export type IndicatorProduct = Database["public"]["Tables"]["indicator_products"]["Row"];
export type ProjectPerformanceUpdate = Database["public"]["Tables"]["project_performance_updates"]["Row"];
export type Comment = Database["public"]["Tables"]["comments"]["Row"];
export type Notification = Database["public"]["Tables"]["notifications"]["Row"];
export type AutomationLog = Database["public"]["Tables"]["automation_logs"]["Row"];
export type ProjectTemplate = Database["public"]["Tables"]["project_templates"]["Row"];
export type TaskTemplate = Database["public"]["Tables"]["task_templates"]["Row"];
